name: First Workflow
on: workflow_dispatch #event = manually trigger workflow.'on' tells when should this wf should run. github actions has many other events
jobs: 
  first-job:  # custom job name, we  named ours as first-job
    runs-on: ubuntu-latest # runner or environment , this is reserved key
    steps: # reserved word
      - name: Print greeting
        run: echo "Hello World !"
      - name: Print goodbye
        run: echo "Done - bye!!"
      - name : Multi-line output If you need to run multiple shell commands (or multi-line commands, e.g., for readability), you can easily do so by adding the pipe symbol (|) as a value after the run key.
        run: |
            echo "First output"
            echo "Second output"
      
